ssad911/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('system.urls')),
    path('admin/', admin.site.urls),
]

system/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

from django.conf.urls import url

app_name = 'system'

urlpatterns = [
	# This is the first page when user doesn't have any extension and will be redirected to login page
    path('', views.blank, name='blank'),

	# Login Page
	path('login',auth_views.login),

	# Logout Page
	url(r'^logout/$', views.logout, {'next_page': '/'}, name='logout'),

	# Main page after login with checking at views.py
    path('home',views.main_page, name='home'),

	# Add Report
	url( r'report/add/$', views.ReportView.as_view(), name='report-add'),

    url( r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # Pull all reports belonging to the supervisor
    url( r'^ajax/supervisor_reports/$', views.retrieveSupervisorReports, name='supervisorReports'),

    # Check if CMO LO authentication
    url( r'^ajax/check_Authentication/$', views.checkAccountAuth, name='checkAuthentication'),

    #Pull all reports
    url(  r'^ajax/all_reports/$', views. retrieveAllReports, name='allReports'),

    #Modify Report
	url(  r'^ajax/modify_Report/$', views.modifyReport, name='modifyReport'),

    #Delete Report
    url(  r'^delete_report/(?P<myPk>[0-9]+)/$', views. deleteReport, name='deleteReport'),

    #Send to CMO
    url(  r'^send_to_CMO/(?P<myPk>[0-9]+)/$', views.sendToCMO, name='sendToCMO'),

    # API for CMO to pull reports
    url('test/(?P<token>[\w\.-]+)', views.CMOPull, name='CMOPull')
]

system/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class IncidentReport( models.Model ):
	phone_number = models.CharField(max_length=10)
	nric = models.CharField(max_length=10)
	datetime = models.DateTimeField(auto_now_add=True)
	title = models.TextField(max_length=2000) #change to title
	detail = models.TextField(max_length=10000) #change to title
	location = models.CharField(max_length=1000)
	emergency_level = models.IntegerField(default=1)
	status = models.CharField(max_length=100)
	assigned_to_supervisor = models.CharField(max_length=100)
	longitude = models.FloatField(default=1.3483099)
	latitude = models.FloatField(default=103.68313469999998)

	def get_absolute_url(self):
		return reverse( 'system:detail', kwargs={'pk': self.pk} )

	def __str__( self ):
		 return 'ID: %s, %s %s' % (self.pk,self.phone_number, self.datetime)


from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Role(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	job = models.TextField(max_length=20, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Role.objects.create(user=instance, job='operator')

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.role.save()

system/forms.py
from django import forms
from .models import IncidentReport

EMERGENCY_LEVEL = (
    (1,'LEVEL 1'),
    (2, 'LEVEL 2'),
    (3,'LEVEL 3'),
)

# Modal Form is bound compared to forms.Form
class AddReportForm( forms.ModelForm ):
	phone_number = forms.CharField( max_length = 10 )
	title = forms.CharField( required = True, widget= forms.TextInput, max_length=1000 )
	detail = forms.CharField(required=True, widget=forms.Textarea(attrs={'rows': 2, 'cols': 40}))
	location = forms.CharField( max_length=1000 )
	emergency_level = forms.ChoiceField( choices = EMERGENCY_LEVEL )
	longitude = forms.CharField(widget=forms.HiddenInput(), initial=1.3483099)
	latitude = forms.CharField(widget=forms.HiddenInput(), initial=103.68313469999998)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in iter(self.fields):
			self.fields[field].widget.attrs.update({
				'class': 'form-control'
			})
        
		self.fields['phone_number'].widget.attrs\
			.update({
				'id': 'phone_number',
			})

		self.fields['nric'].widget.attrs \
			.update({
			'id': 'nric',
		})

		self.fields['location'].widget.attrs\
			.update({
				'id': 'location',
			})
		self.fields['longitude'].widget.attrs\
			.update({
				'id': 'longitude',
			})
		self.fields['latitude'].widget.attrs\
			.update({
				'id': 'latitude',
			})
	
	class Meta: 
		model = IncidentReport
		fields = ['phone_number','nric','title', 'detail', 'location','emergency_level','longitude','latitude' ]

system/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import IncidentReport
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.views import generic
from .forms import AddReportForm
import requests

def blank(request):
    return redirect('/login')

# Create your views here.
def main_page(request):
    global queuedReportsList
    global mylist

    context = {  # some data we might wanna pass over
        'username': request.user.get_username,
        'all_reports': IncidentReport.objects.all()
    }

    #check the user is logged in
    #else redirect to login page
    if request.user.is_authenticated:
        # retrieve the person's role and redirect accordingly
        if(request.user.role.job == 'operator'):
            return render(request, 'system/operator.html', context)
        elif(request.user.role.job == 'supervisor'):
            mylist.add_user(request.user.get_username())

            #event that there are reports from when oeprators submit reports while there are no supervisors online
            #assign them all to the guy who logs in and empty the list
            if(len(queuedReportsList) > 0):
                for i in queuedReportsList:
                    i.assigned_to_supervisor = request.user.get_username()
                    i.save()
                queuedReportsList = []

            return render(request, 'system/supervisor.html', context)
        else:
            return redirect('/login')
    else:
        return redirect('/login')

from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout
def logout(request, next_page):
    if(request.user.role.job == 'supervisor'):
        mylist.remove_user(request.user.get_username())
    return auth_views.logout(request, next_page)


class ReportView( generic.TemplateView ):
    template_name = 'system/incidentreport_form.html'

    def get( self, request ):
        form = AddReportForm()
        return render( request, self.template_name, {'form': form} )

    def post( self, request ):
        form = AddReportForm( request.POST )
        if form.is_valid(): #code for saving a form to the database
            post = form.save(commit=False)
            post.user = request.user
            post.status = 'pending'

            #not really used??
            phone_number = form.cleaned_data['phone_number']
            title = form.cleaned_data['title']
            detail = form.cleaned_data['detail']
            location = form.cleaned_data['location']
            emergency_level = form.cleaned_data['emergency_level']
            longitude = form.cleaned_data['longitude']
            latitude = form.cleaned_data['latitude']

            supervisorToAssignTo = mylist.get_next_in_list()
            if(supervisorToAssignTo == ''):
                post.assigned_to_supervisor = ''
                queuedReportsList.append(post)
            else:
                post.assigned_to_supervisor = supervisorToAssignTo

            form.save()
            return redirect( 'system:home' )
        #in event the form is invalid, return him to his current page?
        args = { 'form': form, 'phone_number': phone_number, 'title': title, 'detail': detail, 'location': location, 'emergency_level': emergency_level, 'longitude':longitude, 'latitude':latitude}
        return render( request,self.template_name, args )


class DetailView( generic.DetailView ):
    model = IncidentReport
    template_name = 'system/detail.html'



class OnlineList:
  def __init__(self):
    self.supervisor_list = []
    pass

  def add_user(self, x):
      if(x not in self.supervisor_list):
          self.supervisor_list.insert(0, x)
          print("Online Users: ", self.supervisor_list)

  def remove_user(self, x):
    if(x in self.supervisor_list):
        self.supervisor_list.remove(x)
        print(x, "went offline!")


  def get_next_in_list(self):
      #in event there is no supervisors online
      if(len(self.supervisor_list) == 0): return ''
      user = self.supervisor_list.pop(0)
      self.supervisor_list.append(user)
      return user

mylist = OnlineList()
queuedReportsList = []

from django.core.serializers import serialize
from django.core.serializers.json import DjangoJSONEncoder
import json

#For CMO LO authentication widget
def checkAccountAuth(request):
    postUsername = request.POST.get( 'uname' )
    postPassword = request.POST.get( 'psw' )
    myPk = request.POST.get('pk')
    user = authenticate( username=postUsername, password=postPassword )

    if user is not None:
        result = User.objects.filter( username=postUsername, password=postPassword )
        report = IncidentReport.objects.get(pk=myPk)
        report.status = 'authenticatedByCMOLO'
        report.save()
        return HttpResponse(serialize('json', result, cls=DjangoJSONEncoder), content_type="application/json")

    return HttpResponse( 'No user found', status=401 )

from itertools import chain

def retrieveSupervisorReports(ajaxObject):
    username = ajaxObject.GET.get('username', None)
    result = IncidentReport.objects.filter(assigned_to_supervisor=username, status='pending') #.order_by('-emergency_level')
    result2 = IncidentReport.objects.filter(assigned_to_supervisor=username, status='authenticatedByCMOLO').order_by('-emergency_level')
    result_list = list(chain(result, result2))
    return HttpResponse(serialize('json', result_list, cls=DjangoJSONEncoder), content_type="application/json")

def retrieveAllReports(x):
    result = IncidentReport.objects.all()
    return HttpResponse(serialize('json', result, cls=DjangoJSONEncoder), content_type="application/json")

def modifyReport(request):
    id = request.POST.get("pk")
    title = request.POST.get("title")
    detail = request.POST.get("detail")
    location = request.POST.get("location")
    emergency_level = request.POST.get("emergency_level")

    #modify report in DB
    result = IncidentReport.objects.all()
    report = IncidentReport.objects.get(pk=id)
    report.location = location
    report.emergency_level = emergency_level
    report.status = 'pending'
    report.title = title
    report.detail = detail
    report.save()
    return HttpResponse(serialize('json', result, cls=DjangoJSONEncoder), content_type="application/json")

def deleteReport(request, myPk):
    #delete report in DB
    report = IncidentReport.objects.get(pk=myPk)
    report.delete()

    # redirect user back to his page
    context = {
        'username': request.user.get_username
    }
    return render(request, 'system/supervisor.html', context)

def sendToCMO(request, myPk):
    report = IncidentReport.objects.get(pk=myPk)
    report.status = 'loadedToAPI'
    report.save()
    context = {
        'username': request.user.get_username
    }
    return render(request, 'system/supervisor.html', context)

    ''' Not needed anymore, since we are doing GET
    # create an object to send, with the fields as agreed by the other team leads
    objectToSend = {}
    #  objectToSend['incident_id'] = report.pk
    #  objectToSend['incident_date_time'] = str(report.datetime)
    #  objectToSend['incident_phone'] = report.phone_number
    objectToSend['location'] = report.location
    objectToSend['detail'] = report.detail
    objectToSend['title'] = report.title
    # objectToSend['incident_NRIC'] = report.nric
    objectToSend['emergency_level'] = report.emergency_level
    objectToSend = json.dumps(objectToSend)

    # send to CMO, check with Hans for CMO's URL
    # with a POST request, rmb to set (Static) token for verification
    try:
        response = requests.post(
            'http://10.27.241.103:8000/api/notifs/?username=911&api_key=84a639c34e3b103172cbe1738e00b5edbeb0fb11',
            headers={'Content-Type': 'application/json'}, data=objectToSend)
        reply = response.content  # handle acknowledge? ignore for now
    except:
        print("error in sending!")
    # redirect user back to his page
    context = {
        'username': request.user.get_username
    }
    return render(request, 'system/supervisor.html', context)
    '''



#CMO is to GET from us
#only the fields: location, detail, title, emergency_level, lat, lon
#datetime, pk/id?
def CMOPull(request, token):
    if(token == '84a639c34e3b103172cbe1738e00b5edbeb0fb11'):
        reports = IncidentReport.objects.filter(status='loadedToAPI', emergency_level=3)
        dataToSend = reports.only('location', 'detail', 'title', 'emergency_level','latitude', 'longitude')
        dataToSend = serialize('json', dataToSend, cls=DjangoJSONEncoder)
        print('json to send:', dataToSend)
        #reports.update(status='sentToCMO') #disable for initial GET testing, as the reports will always disappear
        print(reports)
        return HttpResponse(dataToSend, content_type='application/json')
    else:
        return HttpResponse('Token Authentication Error!')
    ''' to call our GET API, the following code should work
    response = requests.get('http://localhost:8080/test',  headers={'Content-Type': 'application/json'})
    import json
    reply = json.loads(response.content)
    print(reply)
    '''


'''
#for testing only
def CMOPull(request):
    reports = IncidentReport.objects.filter(status='sentToCMO')
    dataToSend = serialize('json', reports, cls=DjangoJSONEncoder)
    return HttpResponse(dataToSend, content_type='application/json')
'''

system/templates/system/detail.html
{% extends 'base.html' %}
{% block title %}Incident Report{% endblock %}

{% block body %}

    <!--Create Incident Report Form-->
	<div class="card card-register mx-auto mt-5">
		<div class="card-header">Incident Report Detail</div>
		<div class="card-body">
			<h3>Caller Phone Number:</h3><p> {{ incidentreport.phone_number  }}</p>
			<h3>NRIC:</h3><p> {{ incidentreport.nric  }}</p>
			<h3>Description of Incident:</h3><p> {{ incidentreport.detail  }}</p>
			<h3>Location of Incident:</h3><p> {{ incidentreport.location  }}</p>
			<h3>Emergency Level:</h3><p> {{ incidentreport.emergency_level  }}</p>
		</div>
	</div>

{% endblock body %}

system/templates/system/operator.html
{% extends 'base.html' %}

{% block body %}

    <!--Create Incident Report Form-->
	<div class="card card-register mx-auto mt-5" style="margin-bottom: 75px;">
		<div class="card-header">Incident Reports
         <a href="{% url 'system:report-add' %}" class="btn btn-primary btn-sm" role="button">Create Incident Report</a>
		</div>
		{% for report in all_reports %}
			<div class="card-body">
				<div class="thumbnail">
					<a href="{% url 'system:detail' report.id %}"></a>
					<div class="caption">
						<h4>Phone No: {{ report.phone_number }}</h4>
						<h4>Location: {{ report.location }}</h4>

						<!-- View Details -->
						<a href="{% url 'system:detail' report.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

						<!-- Delete Album -->
						<form action="" method="post" style="display: inline;">
							{% csrf_token %}
							<input type="hidden" name="report_id" value="{{ report.id }}" />
							<button type="submit" class="btn btn-default btn-sm">
								<span class="glyphicon glyphicon-trash"></span>
							</button>
						</form>
					</div>
				</div>
			</div>
			{% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
		{% endfor %}
	</div>

{% endblock body %}

system/templates/system/supervisor.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block body %}

{% block javascript %}
  <script>
	  var selectedReportID = -1;
	  var reportList = 0;
	  var cache = 0;
	  var selected = 0;

	  var username = '{{ username }}';
	  var ModifyURL = -1;
	  var DeleteURL = -1;
	  var SendToCMOURL = -1;
		
	  var initialTimeOut;
	  
	function loadForm(reportID){
		var report = cache[reportID];
		var formElement =  $("#report");
		var titleElement = formElement.find('#fname');
		var locationElement = formElement.find('#lname');
		var eLvlElement = formElement.find('#eLvl');
		var detailElement = formElement.find('#detail');
		
		titleElement.val(report.fields.title)
		locationElement.val(report.fields.location)
		eLvlElement.val(report.fields.emergency_level)
		detailElement.val(report.fields.detail)
		
        if( report.fields.status == 'authenticatedByCMOLO' || document.getElementById("eLvl").value != 3 ) {
          document.getElementById("authenticateBtn").disabled = true;
          document.getElementById("sendCMObtn").disabled = false;
        } else {
          document.getElementById("authenticateBtn").disabled = false;
          document.getElementById("sendCMObtn").disabled = true;
        }

		selectedReportID = report.pk
		DeleteURL = "{% url 'system:deleteReport' myPk=1234 %}".replace(/1234/, selectedReportID.toString());
		SendToCMOURL = "{% url 'system:sendToCMO' myPk=1234 %}".replace(/1234/, selectedReportID.toString());
		
	}

	function pullSupervisorReports(shouldLoadForm=false){
      $.ajax({
        url: '/ajax/supervisor_reports/',
        data: {
          'username': username
        },
        dataType: 'json',
        success: function (data) {
			cache = data;
			reportList.empty();
			data.forEach((report, index) => {
				 var li = document.createElement("li");
				 if( report.fields.emergency_level == 3 ) {
						li.className += "list-group-item list-group-item-danger";
					} else if( report.fields.emergency_level == 2) {
						li.className += "list-group-item list-group-item-warning";
					} else {
						li.className += "list-group-item list-group-item-info";
					}
				 li.innerHTML += "<a class='reportItem'> " + report.fields.title + " @ " +report.fields.location + "\n" + report.fields.datetime.substring(0,10) + ' ' + report.fields.datetime.substring(11,19) + " </a>";
				 reportList.append(li);
			});//end of for each
						$('#myUL li').click(function(){ loadForm($(this).index()); selected = $(this).index();});
						if(shouldLoadForm){ loadForm(selected); }
						console.log(selected)
			}//end of ajax success
			
		});//end of ajax call
	}//end of pullSupervisorReports

	$('document').ready(function(){
		reportList = $("#myUL");
		pullSupervisorReports(false);
		setInterval(pullSupervisorReports, 10000);
		initialTimeOut = setTimeout(loadFormInitial, 500);
        
        // Disable location selection
         document.getElementById("lname").disabled='true';
	}); //end of document ready
	
  function loadFormInitial(){
	  if(cache[selected]){ loadForm(selected)}
      else if (cache[0]) { loadForm(0)}; 
	  clearTimeout(initialTimeOut);
  }
  
  function checkAuthentication() {
	username = document.getElementById("uname").value;
	password = document.getElementById("psw").value;
	pk = cache[selected]['pk']
	
    $.ajax({
      type: 'POST',
      url: '/ajax/check_Authentication/',
	  
      data:  {
				'csrfmiddlewaretoken' : '{{ csrf_token }}',
				'uname' : username,
				'psw' : password,
				'pk': pk
      },
      success: function(data) {
        alert("CMO LO successfully authenticate level 3 crisis !");
        document.getElementById("authenticateBtn").disabled = true;
        document.getElementById("sendCMObtn").disabled = false;
      },
	  error: function (XMLHttpRequest, textStatus, errorThrown) {
			alert('Authentication error!');
		}
    });
	username = '{{ username }}' //somehow the username variable in the javascript becomes CMO_LO, so we need to set it back to the supervisor
  }

	function executeModifyReport(){
		var formElement =  $("#report");
		var titleElement = formElement.find('#fname');
		var locationElement = formElement.find('#lname');
		var eLvlElement = formElement.find('#eLvl');
		var detailElement = formElement.find('#detail');

		var title = titleElement.val()
		var loc = locationElement.val()
		var eLvl = eLvlElement.val()
		var detail = detailElement.val()

		var report = cache[selected];
		selectedReportID = report.pk
		$.ajax({
			type: 'POST',
			url: '/ajax/modify_Report/',
			dataType: 'json',
			data:  {
				'csrfmiddlewaretoken' : '{{ csrf_token }}',
				'pk' : selectedReportID,
				'detail': detail,
				'title': title,
				'location': loc,
				'emergency_level': eLvl
			},

			success: function( data ) {
				alert( "Incident Report is succesfully updated!" );
				pullSupervisorReports(true);
			},
			

		})

	}

  </script>
{% endblock %}

  <div class="content-wrapper" style="margin-bottom: 75px; margin-left: 0px; margin-top: 30px;">
    <div class="container-fluid">
      <div class="row">
  <div class="column">
    <ul class="list-group" id="myUL"></ul>
  </div>
  <div class="column2">
    <form action="/action_page.php" id="report">
			{% csrf_token %}
                <label for="rname">Report Title</label>
                <input class="supReport" type="text" id="fname" name="Title" value="">

                <label for="location">Location</label>
                <input class="supReport" type="text" id="lname" name="lastname" value="">

                <label for="eLvl">Emergency Level</label>
                    <select class="supReport" id="eLvl" name="EmergencyLevel">
                        <option value="1" selected>Level 1</option>
                        <option value="2">Level 2</option>
                        <option value="3">Level 3</option>
                    </select>

                <label for="detail">Details</label>
               <textarea class="supReport" id="detail" name="detail" style="height:200px"></textarea>

                <button id="sendCMObtn" class="btn btn-primary btn-sm" type="button" name="sendToCMO" form="report" onclick="location.href=SendToCMOURL"> Send To CMO </button>
                <button class="btn btn-primary btn-sm" type="button" name="modify" form="report" onclick="executeModifyReport()">Modify</button>
                <button class="btn btn-primary btn-sm" type="button" name="delete" form="report" onclick="location.href=DeleteURL">Delete</button>

            </form>
             <!-- Button to open the modal login form -->
				<button id="authenticateBtn" type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#id01">Authenticate</button>

				<!-- The Modal -->
				<div class="container">
				<div class="modal fade" id="id01" role="dialog">
					<div class="modal-dialog">

					  <!-- Modal content-->
					  <div class="modal-content">
						<div class="modal-header">
						  <h4 class="modal-title">Authenticate</h4>
						  <button type="button" class="close" data-dismiss="modal">&times;</button>
						</div>
						<div class="modal-body">
							<form class="modal-content animate" method="POST" action="" style="border-style: none;">
								{% csrf_token %}
								<label for="uname"><b>Username</b></label>
								<input class="supReport" id="uname" type="text" placeholder="Enter Username" name="uname" required="required"/>

								<label for="psw"><b>Password</b></label>
								<input class="supReport" id="psw" type="password" placeholder="Enter Password" name="psw" required="required"/>

								<button  class="btn btn-primary btn-sm" type="button" onclick="checkAuthentication()" data-dismiss="modal">Authenticate</button>

							</form>
						</div>
						<div class="modal-footer">
						  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						</div>
					  </div>

					</div>
				</div>
				</div>




  </div>
</div>

</div>
	<script> </script>
  </div>
{% endblock body %}