ssad911/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('system.urls')),
    path('admin/', admin.site.urls),
]

system/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

from django.conf.urls import url

app_name = 'system'

urlpatterns = [
	# This is the first page when user doesn't have any extension and will be redirected to login page
    path('', views.blank, name='blank'),

	# Login Page
	path('login',auth_views.login),

	# Logout Page
	url(r'^logout/$', views.logout, {'next_page': '/'}, name='logout'),

	# Main page after login with checking at views.py
    path('home',views.main_page, name='home'),

	# Add Report
	url( r'report/add/$', views.ReportView.as_view(), name='report-add'),

    url( r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # Pull all reports belonging to the supervisor
    url( r'^ajax/supervisor_reports/$', views.retrieveSupervisorReports, name='supervisorReports'),

    # Check if CMO LO authentication
    url( r'^ajax/check_Authentication/$', views.checkAccountAuth, name='checkAuthentication'),

    #Pull all reports
    url(  r'^ajax/all_reports/$', views. retrieveAllReports, name='allReports'),

    #Modify Report
	url(  r'^ajax/modify_Report/$', views.modifyReport, name='modifyReport'),

    #Delete Report
    url(  r'^delete_report/(?P<myPk>[0-9]+)/$', views. deleteReport, name='deleteReport'),

    #Send to CMO
    url(  r'^send_to_CMO/(?P<myPk>[0-9]+)/$', views.sendToCMO, name='sendToCMO'),

    # API for CMO to pull reports
    url('test/(?P<token>[\w\.-]+)', views.CMOPull, name='CMOPull')
]

system/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class IncidentReport( models.Model ):
	phone_number = models.CharField(max_length=10)
	nric = models.CharField(max_length=10)
	datetime = models.DateTimeField(auto_now_add=True)
	title = models.TextField(max_length=2000) #change to title
	detail = models.TextField(max_length=10000) #change to title
	location = models.CharField(max_length=1000)
	emergency_level = models.IntegerField(default=1)
	status = models.CharField(max_length=100)
	assigned_to_supervisor = models.CharField(max_length=100)
	longitude = models.FloatField(default=1.3483099)
	latitude = models.FloatField(default=103.68313469999998)

	def get_absolute_url(self):
		return reverse( 'system:detail', kwargs={'pk': self.pk} )

	def __str__( self ):
		 return 'ID: %s, %s %s' % (self.pk,self.phone_number, self.datetime)


from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Role(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	job = models.TextField(max_length=20, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Role.objects.create(user=instance, job='operator')

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.role.save()

system/forms.py
from django import forms
from .models import IncidentReport

EMERGENCY_LEVEL = (
    (1,'LEVEL 1'),
    (2, 'LEVEL 2'),
    (3,'LEVEL 3'),
)

# Modal Form is bound compared to forms.Form
class AddReportForm( forms.ModelForm ):
	phone_number = forms.CharField( max_length = 10 )
	title = forms.CharField( required = True, widget= forms.TextInput, max_length=1000 )
	detail = forms.CharField(required=True, widget=forms.Textarea(attrs={'rows': 2, 'cols': 40}))
	location = forms.CharField( max_length=1000 )
	emergency_level = forms.ChoiceField( choices = EMERGENCY_LEVEL )
	longitude = forms.CharField(widget=forms.HiddenInput(), initial=1.3483099)
	latitude = forms.CharField(widget=forms.HiddenInput(), initial=103.68313469999998)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in iter(self.fields):
			self.fields[field].widget.attrs.update({
				'class': 'form-control'
			})
        
		self.fields['phone_number'].widget.attrs\
			.update({
				'id': 'phone_number',
			})

		self.fields['nric'].widget.attrs \
			.update({
			'id': 'nric',
		})

		self.fields['location'].widget.attrs\
			.update({
				'id': 'location',
			})
		self.fields['longitude'].widget.attrs\
			.update({
				'id': 'longitude',
			})
		self.fields['latitude'].widget.attrs\
			.update({
				'id': 'latitude',
			})
	
	class Meta: 
		model = IncidentReport
		fields = ['phone_number','nric','title', 'detail', 'location','emergency_level','longitude','latitude' ]

system/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import IncidentReport
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.views import generic
from .forms import AddReportForm
import requests

def blank(request):
    return redirect('/login')

# Create your views here.
def main_page(request):
    global queuedReportsList
    global mylist

    context = {  # some data we might wanna pass over
        'username': request.user.get_username,
        'all_reports': IncidentReport.objects.all()
    }

    #check the user is logged in
    #else redirect to login page
    if request.user.is_authenticated:
        # retrieve the person's role and redirect accordingly
        if(request.user.role.job == 'operator'):
            return render(request, 'system/operator.html', context)
        elif(request.user.role.job == 'supervisor'):
            mylist.add_user(request.user.get_username())

            #event that there are reports from when oeprators submit reports while there are no supervisors online
            #assign them all to the guy who logs in and empty the list
            if(len(queuedReportsList) > 0):
                for i in queuedReportsList:
                    i.assigned_to_supervisor = request.user.get_username()
                    i.save()
                queuedReportsList = []

            return render(request, 'system/supervisor.html', context)
        else:
            return redirect('/login')
    else:
        return redirect('/login')

from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout
def logout(request, next_page):
    if(request.user.role.job == 'supervisor'):
        mylist.remove_user(request.user.get_username())
    return auth_views.logout(request, next_page)


class ReportView( generic.TemplateView ):
    template_name = 'system/incidentreport_form.html'

    def get( self, request ):
        form = AddReportForm()
        return render( request, self.template_name, {'form': form} )

    def post( self, request ):
        form = AddReportForm( request.POST )
        if form.is_valid(): #code for saving a form to the database
            post = form.save(commit=False)
            post.user = request.user
            post.status = 'pending'

            #not really used??
            phone_number = form.cleaned_data['phone_number']
            title = form.cleaned_data['title']
            detail = form.cleaned_data['detail']
            location = form.cleaned_data['location']
            emergency_level = form.cleaned_data['emergency_level']
            longitude = form.cleaned_data['longitude']
            latitude = form.cleaned_data['latitude']

            supervisorToAssignTo = mylist.get_next_in_list()
            if(supervisorToAssignTo == ''):
                post.assigned_to_supervisor = ''
                queuedReportsList.append(post)
            else:
                post.assigned_to_supervisor = supervisorToAssignTo

            form.save()
            return redirect( 'system:home' )
        #in event the form is invalid, return him to his current page?
        args = { 'form': form, 'phone_number': phone_number, 'title': title, 'detail': detail, 'location': location, 'emergency_level': emergency_level, 'longitude':longitude, 'latitude':latitude}
        return render( request,self.template_name, args )


class DetailView( generic.DetailView ):
    model = IncidentReport
    template_name = 'system/detail.html'



class OnlineList:
  def __init__(self):
    self.supervisor_list = []
    pass

  def add_user(self, x):
      if(x not in self.supervisor_list):
          self.supervisor_list.insert(0, x)
          print("Online Users: ", self.supervisor_list)

  def remove_user(self, x):
    if(x in self.supervisor_list):
        self.supervisor_list.remove(x)
        print(x, "went offline!")


  def get_next_in_list(self):
      #in event there is no supervisors online
      if(len(self.supervisor_list) == 0): return ''
      user = self.supervisor_list.pop(0)
      self.supervisor_list.append(user)
      return user

mylist = OnlineList()
queuedReportsList = []

from django.core.serializers import serialize
from django.core.serializers.json import DjangoJSONEncoder
import json

#For CMO LO authentication widget
def checkAccountAuth(request):
    postUsername = request.POST.get( 'uname' )
    postPassword = request.POST.get( 'psw' )
    myPk = request.POST.get('pk')
    user = authenticate( username=postUsername, password=postPassword )

    if user is not None:
        result = User.objects.filter( username=postUsername, password=postPassword )
        report = IncidentReport.objects.get(pk=myPk)
        report.status = 'authenticatedByCMOLO'
        report.save()
        return HttpResponse(serialize('json', result, cls=DjangoJSONEncoder), content_type="application/json")

    return HttpResponse( 'No user found', status=401 )

from itertools import chain

def retrieveSupervisorReports(ajaxObject):
    username = ajaxObject.GET.get('username', None)
    result = IncidentReport.objects.filter(assigned_to_supervisor=username, status='pending') #.order_by('-emergency_level')
    result2 = IncidentReport.objects.filter(assigned_to_supervisor=username, status='authenticatedByCMOLO').order_by('-emergency_level')
    result_list = list(chain(result, result2))
    return HttpResponse(serialize('json', result_list, cls=DjangoJSONEncoder), content_type="application/json")

def retrieveAllReports(x):
    result = IncidentReport.objects.all()
    return HttpResponse(serialize('json', result, cls=DjangoJSONEncoder), content_type="application/json")

def modifyReport(request):
    id = request.POST.get("pk")
    title = request.POST.get("title")
    detail = request.POST.get("detail")
    location = request.POST.get("location")
    emergency_level = request.POST.get("emergency_level")

    #modify report in DB
    result = IncidentReport.objects.all()
    report = IncidentReport.objects.get(pk=id)
    report.location = location
    report.emergency_level = emergency_level
    report.status = 'pending'
    report.title = title
    report.detail = detail
    report.save()
    return HttpResponse(serialize('json', result, cls=DjangoJSONEncoder), content_type="application/json")

def deleteReport(request, myPk):
    #delete report in DB
    report = IncidentReport.objects.get(pk=myPk)
    report.delete()

    # redirect user back to his page
    context = {
        'username': request.user.get_username
    }
    return render(request, 'system/supervisor.html', context)

def sendToCMO(request, myPk):
    report = IncidentReport.objects.get(pk=myPk)
    report.status = 'loadedToAPI'
    report.save()
    context = {
        'username': request.user.get_username
    }
    return render(request, 'system/supervisor.html', context)

    ''' Not needed anymore, since we are doing GET
    # create an object to send, with the fields as agreed by the other team leads
    objectToSend = {}
    #  objectToSend['incident_id'] = report.pk
    #  objectToSend['incident_date_time'] = str(report.datetime)
    #  objectToSend['incident_phone'] = report.phone_number
    objectToSend['location'] = report.location
    objectToSend['detail'] = report.detail
    objectToSend['title'] = report.title
    # objectToSend['incident_NRIC'] = report.nric
    objectToSend['emergency_level'] = report.emergency_level
    objectToSend = json.dumps(objectToSend)

    # send to CMO, check with Hans for CMO's URL
    # with a POST request, rmb to set (Static) token for verification
    try:
        response = requests.post(
            'http://10.27.241.103:8000/api/notifs/?username=911&api_key=84a639c34e3b103172cbe1738e00b5edbeb0fb11',
            headers={'Content-Type': 'application/json'}, data=objectToSend)
        reply = response.content  # handle acknowledge? ignore for now
    except:
        print("error in sending!")
    # redirect user back to his page
    context = {
        'username': request.user.get_username
    }
    return render(request, 'system/supervisor.html', context)
    '''



#CMO is to GET from us
#only the fields: location, detail, title, emergency_level, lat, lon
#datetime, pk/id?
def CMOPull(request, token):
    if(token == '84a639c34e3b103172cbe1738e00b5edbeb0fb11'):
        reports = IncidentReport.objects.filter(status='loadedToAPI', emergency_level=3)
        dataToSend = reports.only('location', 'detail', 'title', 'emergency_level','latitude', 'longitude')
        dataToSend = serialize('json', dataToSend, cls=DjangoJSONEncoder)
        print('json to send:', dataToSend)
        #reports.update(status='sentToCMO') #disable for initial GET testing, as the reports will always disappear
        print(reports)
        return HttpResponse(dataToSend, content_type='application/json')
    else:
        return HttpResponse('Token Authentication Error!')
    ''' to call our GET API, the following code should work
    response = requests.get('http://localhost:8080/test',  headers={'Content-Type': 'application/json'})
    import json
    reply = json.loads(response.content)
    print(reply)
    '''


'''
#for testing only
def CMOPull(request):
    reports = IncidentReport.objects.filter(status='sentToCMO')
    dataToSend = serialize('json', reports, cls=DjangoJSONEncoder)
    return HttpResponse(dataToSend, content_type='application/json')
'''

system/templates/base.html
{% load static from staticfiles %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>NESIMS - 911</title>
  <!-- Bootstrap core CSS-->
  <link href="{%  static 'vendor/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="{%  static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="{%  static 'css/sb-admin.css' %}" rel="stylesheet">
  <link href="{%  static 'system/style2.css' %}" rel="stylesheet">
  <!-- Bootstrap core JavaScript-->
  <script src="{%  static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{%  static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- Core plugin JavaScript-->
  <script src="{%  static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <!-- Custom scripts for all pages-->
  <script src="{%  static 'js/sb-admin.min.js' %}"></script>
</head>
<body>
  <!--Navigation bar
    <div id="nav-placeholder"></div>
    <script>
    $(function(){
      $("#nav-placeholder").load("base.html");
    });
    </script>
  end of Navigation bar-->
<div class="container">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{% url 'system:home' %}">NESIMS - 911</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarResponsive">
    
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-fw fa-envelope"></i>
                    <span class="d-lg-none">Messages
                        <span class="badge badge-pill badge-primary">12 New</span>
                    </span>
                    <span class="indicator text-primary d-none d-lg-block">
                        <i class="fa fa-fw fa-circle"></i>
                    </span>
                </a>
                <div class="dropdown-menu" aria-labelledby="messagesDropdown">
                    <h6 class="dropdown-header">New Messages:</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <strong>David Miller</strong>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <strong>Jane Smith</strong>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <strong>John Doe</strong>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item small" href="#">View all messages</a>
                </div>
            </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-bell"></i>
            <span class="d-lg-none">Alerts
              <span class="badge badge-pill badge-warning">6 New</span>
            </span>
            <span class="indicator text-warning d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="alertsDropdown">
            <h6 class="dropdown-header">New Alerts:</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong>
                  <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-danger">
                <strong>
                  <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong>
                  <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item small" href="#">View all alerts</a>
          </div>
        </li>
        <li class="nav-item">
          <form class="form-inline my-2 my-lg-0 mr-lg-2">
            <div class="input-group">
              <input class="form-control" type="text" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fa fa-search"></i>
                </button>
              </span>
            </div>
          </form>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
        </li>
      </ul>
    </div>
  </nav>




    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{%url 'system:logout'%}">Logout</a>
          </div>
        </div>
      </div>
    </div>
</div>
{% block body %}
{% endblock %}
</body>
</html>